const HostelsFakeData = [
    {
        id: "1",
        location: "Cox's Bazar, Chittagong Division, Bangladesh",
        title: "Entire serviced apartment hosted by Arafat",
        guests: '4',
        bedrooms: '1',
        beds: '1',
        baths: '1',
        price: '38',
        cleaningFee: '10',
        serviceFee: '21',
        star: '1',
        network: 'Wifi Air conditioning Kitchen',
        status: 'Cancellation flexibility available',
        hostelOwnerName: 'Mahbub Hasan',
        hostelOwnerPhoto: 'https://i.imgur.com/55KK3EO.jpg',
        hostelPhoto: {
            img1: "https://i.imgur.com/Dgep3pc.jpg",
            img2: "https://i.imgur.com/3wMX4rT.jpg",
            img3: "https://i.imgur.com/Xvz0RLi.jpg",
            img4: "https://i.imgur.com/NWeOx5D.jpg",
            img5: "https://i.imgur.com/SGY4EYn.jpg",
        },
        Description: "Luxurious room at The Hotel Cox-today near Shugandha Beach at cox bazar furnished with exclusive comfortable bed, interior design, hill side view, Ac,Wifi,geyser, freeze, card punch door lock with self check-in, free breakfast & free sweeming.",
    },
    {
        id: '2',
        location: "Cox's Bazar, Chittagong Division, Bangladesh",
        title: "Private room in guest suite hosted by Umme Kulsum",
        guests: '3',
        bedrooms: '1',
        beds: '1',
        baths: '1',
        prise: '15',
        cleaningFee: '10',
        serviceFee: '21',
        star: '12',
        network: "Wifi Air conditioning Kitchen",
        status: "Cancellation flexibility available",
        hostelOwnerName: "",
        hostelOwnerPhoto: "https://i.imgur.com/Wubsurq.jpg",
        hostelPhoto: {
            img1: "https://i.imgur.com/7Tsufcw.jpg",
            img2: "https://i.imgur.com/jDplOm3.jpg",
            img3: "https://i.imgur.com/0K9GxBj.jpg",
            img4: "https://i.imgur.com/m2YTjzq.jpg",
            img5: "https://i.imgur.com/CjGaeMo.jpg",
        },
        Description: "This property is located in the center of the city. It is close to everything. The beach is 7-10 minutes away by rikshaw. This room is a part of a big building and there is always someone around to help.----||---, The room has separate entrance but attached bathroom and kitchen. This is unique because you feel like you are staying at home. This property is close to everything and very easy to get cheap transportation. ----||----, Guests can use roof, yard, pond and mosque. There are few shops where guests can get there necessary stuffs. The location is very easy and known by everyone.",
    },
    {
        id: '3',
        location: "Chittagong, Chittagong Division, Bangladesh",
        title: "Entire apartment hosted by Harun",
        guests: "6",
        bedrooms: "3",
        beds: "3",
        baths: "3",
        price: "35",
        cleaningFee: '10',
        serviceFee: '21',
        star: "49",
        network: "Wifi Air conditioning Kitchen",
        status: "Cancellation flexibility available",
        hostelOwnerName: "",
        hostelOwnerPhoto: "https://i.imgur.com/SszvkAa.jpg",
        hostelPhoto: {
            img1: "https://i.imgur.com/yXMlO1i.jpg",
            img2: "https://i.imgur.com/Fqp7YYn.jpg",
            img3: "https://i.imgur.com/XDCLG0M.jpg",
            img4: "https://i.imgur.com/L47rqf7.jpg",
            img5: "https://i.imgur.com/h7neaIS.jpg",
        },
        Description: "",
    },
    {
        id: '4',
        location: "Sylhet, Sylhet Division, Bangladesh",
        title: "Private room in apartment hosted by Wahiduzzaman",
        guests: "2",
        bedrooms: "1",
        beds: "1",
        baths: "1",
        price: "18",
        cleaningFee: '10',
        serviceFee: '21',
        star: "0",
        network: "Wifi Air conditioning Kitchen",
        status: "Cancellation flexibility available",
        hostelOwnerName: "Wahiduzzaman",
        hostelOwnerPhoto: "https://i.imgur.com/pmaDwPT.jpg",
        hostelPhoto: {
            img1: "https://i.imgur.com/iCraeb2.jpg",
            img2: "https://i.imgur.com/HsTxtBZ.jpg",
            img3: "https://i.imgur.com/sHyBraX.jpg",
            img4: "https://i.imgur.com/k89dEJO.jpg",
            img5: "https://i.imgur.com/Fsu8TsC.jpg",
        },
        Description: "",
    },
    {
        id: '5',
        location: "Sylhet, Sylhet Division, Bangladesh",
        title: "Entire apartment hosted by Iqbal",
        guests: "6",
        bedrooms: "3",
        beds: "2",
        baths: "2",
        price: "20",
        cleaningFee: '10',
        serviceFee: '21',
        star: "1",
        network: "Wifi Air conditioning Kitchen",
        status: "Cancellation flexibility available",
        hostelOwnerName: "Fakih Mahmood",
        hostelOwnerPhoto: "https://i.imgur.com/hejEcAY.png",
        hostelPhoto: {
            img1: "https://i.imgur.com/DTDwmYI.jpg",
            img2: "https://i.imgur.com/hUY6tjE.jpg",
            img3: "https://i.imgur.com/zt5DN8D.jpg",
            img4: "https://i.imgur.com/dOOViyO.jpg",
            img5: "https://i.imgur.com/zt5DN8D.jpg",
        },
        Description: "I enjoy travelling and appreciate finding a home away from home. I would never rent a place I wouldn't be willing to stay in myself. you can expect high quality and above all a clean environment. please contact me if you require any further information.",
    },
    {
        id: "6",
        location: "Cox's Bazar, Chittagong Division, Bangladesh",
        title: "Entire serviced apartment hosted by Arafat",
        guests: '4',
        bedrooms: '1',
        beds: '1',
        baths: '1',
        price: '38',
        cleaningFee: '10',
        serviceFee: '21',
        star: '1',
        network: 'Wifi Air conditioning Kitchen',
        status: 'Cancellation flexibility available',
        hostelOwnerName: 'Mahbub Hasan',
        hostelOwnerPhoto: 'https://i.imgur.com/55KK3EO.jpg',
        hostelPhoto: {
            img1: "https://i.imgur.com/Dgep3pc.jpg",
            img2: "https://i.imgur.com/3wMX4rT.jpg",
            img3: "https://i.imgur.com/Xvz0RLi.jpg",
            img4: "https://i.imgur.com/NWeOx5D.jpg",
            img5: "https://i.imgur.com/SGY4EYn.jpg",
        },
        Description: "Luxurious room at The Hotel Cox-today near Shugandha Beach at cox bazar furnished with exclusive comfortable bed, interior design, hill side view, Ac,Wifi,geyser, freeze, card punch door lock with self check-in, free breakfast & free sweeming.",
    },
    {
        id: '7',
        location: "Cox's Bazar, Chittagong Division, Bangladesh",
        title: "Private room in guest suite hosted by Umme Kulsum",
        guests: "3",
        bedrooms: "1",
        beds: "2",
        baths: "1",
        price: "15",
        cleaningFee: '10',
        serviceFee: '21',
        star: "12",
        network: "Wifi Air conditioning Kitchen",
        status: "Cancellation flexibility available",
        hostelOwnerName: "",
        hostelOwnerPhoto: "https://i.imgur.com/Wubsurq.jpg",
        hostelPhoto: {
            img1: "https://i.imgur.com/7Tsufcw.jpg",
            img2: "https://i.imgur.com/jDplOm3.jpg",
            img3: "https://i.imgur.com/0K9GxBj.jpg",
            img4: "https://i.imgur.com/m2YTjzq.jpg",
            img5: "https://i.imgur.com/CjGaeMo.jpg",
        },
        Description: "This property is located in the center of the city. It is close to everything. The beach is 7-10 minutes away by rikshaw. This room is a part of a big building and there is always someone around to help.----||---, The room has separate entrance but attached bathroom and kitchen. This is unique because you feel like you are staying at home. This property is close to everything and very easy to get cheap transportation. ----||----, Guests can use roof, yard, pond and mosque. There are few shops where guests can get there necessary stuffs. The location is very easy and known by everyone.",
    },
    {
        id: '8',
        location: "Chittagong, Chittagong Division, Bangladesh",
        title: "Entire apartment hosted by Harun",
        guests: "6",
        bedrooms: "3",
        beds: "3",
        baths: "3",
        price: "35",
        cleaningFee: '10',
        serviceFee: '21',
        star: "49",
        network: "Wifi Air conditioning Kitchen",
        status: "Cancellation flexibility available",
        hostelOwnerName: "",
        hostelOwnerPhoto: "https://i.imgur.com/SszvkAa.jpg",
        hostelPhoto: {
            img1: "https://i.imgur.com/yXMlO1i.jpg",
            img2: "https://i.imgur.com/Fqp7YYn.jpg",
            img3: "https://i.imgur.com/XDCLG0M.jpg",
            img4: "https://i.imgur.com/L47rqf7.jpg",
            img5: "https://i.imgur.com/h7neaIS.jpg",
        },
        Description: "",
    },
    {
        id: '9',
        location: "Sylhet, Sylhet Division, Bangladesh",
        title: "Private room in apartment hosted by Wahiduzzaman",
        guests: "2",
        bedrooms: "1",
        beds: "1",
        baths: "1",
        price: "18",
        cleaningFee: '10',
        serviceFee: '21',
        star: "0",
        network: "Wifi Air conditioning Kitchen",
        status: "Cancellation flexibility available",
        hostelOwnerName: "Wahiduzzaman",
        hostelOwnerPhoto: "https://i.imgur.com/pmaDwPT.jpg",
        hostelPhoto: {
            img1: "https://i.imgur.com/iCraeb2.jpg",
            img2: "https://i.imgur.com/HsTxtBZ.jpg",
            img3: "https://i.imgur.com/sHyBraX.jpg",
            img4: "https://i.imgur.com/k89dEJO.jpg",
            img5: "https://i.imgur.com/Fsu8TsC.jpg",
        },
        Description: "",
    },
    {
        id: '10',
        location: "Sylhet, Sylhet Division, Bangladesh",
        title: "Entire apartment hosted by Iqbal",
        guests: "6",
        bedrooms: "3",
        beds: "2",
        baths: "2",
        price: "20",
        cleaningFee: '10',
        serviceFee: '21',
        star: "1",
        network: "Wifi Air conditioning Kitchen",
        status: "Cancellation flexibility available",
        hostelOwnerName: "Fakih Mahmood",
        hostelOwnerPhoto: "https://i.imgur.com/hejEcAY.png",
        hostelPhoto: {
            img1: "https://i.imgur.com/DTDwmYI.jpg",
            img2: "https://i.imgur.com/hUY6tjE.jpg",
            img3: "https://i.imgur.com/zt5DN8D.jpg",
            img4: "https://i.imgur.com/dOOViyO.jpg",
            img5: "https://i.imgur.com/zt5DN8D.jpg",
        },
        Description: "I enjoy travelling and appreciate finding a home away from home. I would never rent a place I wouldn't be willing to stay in myself. you can expect high quality and above all a clean environment. please contact me if you require any further information.",
    },
]

export default HostelsFakeData;